//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleWaveNotifier.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InterfaceText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InterfaceText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoogleWaveNotifier.Languages.InterfaceText", typeof(InterfaceText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balloon Timeout.
        /// </summary>
        internal static string BalloonTimeout {
            get {
                return ResourceManager.GetString("BalloonTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter how long (in seconds) the balloon notifications should remain on screen. Please note that Windows may override this setting..
        /// </summary>
        internal static string BalloonTimeoutDescription {
            get {
                return ResourceManager.GetString("BalloonTimeoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Interval.
        /// </summary>
        internal static string CheckInterval {
            get {
                return ResourceManager.GetString("CheckInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter how often (in minutes) Google Wave Notifier should check for new messages..
        /// </summary>
        internal static string CheckIntervalDescription {
            get {
                return ResourceManager.GetString("CheckIntervalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check interval must be 5 minutes or greater..
        /// </summary>
        internal static string CheckIntervalWarningText {
            get {
                return ResourceManager.GetString("CheckIntervalWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Check Now.
        /// </summary>
        internal static string CheckNow {
            get {
                return ResourceManager.GetString("CheckNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Wave Notifier is not an official Google application, nor is it affiliated with Google in any way..
        /// </summary>
        internal static string GoogleAffiliationDisclaimer {
            get {
                return ResourceManager.GetString("GoogleAffiliationDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Translate.
        /// </summary>
        internal static string HelpTranslate {
            get {
                return ResourceManager.GetString("HelpTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Details.
        /// </summary>
        internal static string LoginDetails {
            get {
                return ResourceManager.GetString("LoginDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login to Google Wave. Please check your username, password and proxy settings. See the ErrorLog for more details..
        /// </summary>
        internal static string LoginFailedDescription {
            get {
                return ResourceManager.GetString("LoginFailedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Messages in Google Wave.
        /// </summary>
        internal static string NewMessages {
            get {
                return ResourceManager.GetString("NewMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has 1 unread message..
        /// </summary>
        internal static string NewMessagesDescription1 {
            get {
                return ResourceManager.GetString("NewMessagesDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has {1} unread messages..
        /// </summary>
        internal static string NewMessagesDescription2to4 {
            get {
                return ResourceManager.GetString("NewMessagesDescription2to4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has {1} unread messages..
        /// </summary>
        internal static string NewMessagesDescription5plus {
            get {
                return ResourceManager.GetString("NewMessagesDescription5plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} unread messages across {1} waves..
        /// </summary>
        internal static string NewMessagesTooltipPlural {
            get {
                return ResourceManager.GetString("NewMessagesTooltipPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have 1 unread message..
        /// </summary>
        internal static string NewMessagesTooltipSingleMessage {
            get {
                return ResourceManager.GetString("NewMessagesTooltipSingleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} unread messages in 1 wave..
        /// </summary>
        internal static string NewMessagesTooltipSingleWave {
            get {
                return ResourceManager.GetString("NewMessagesTooltipSingleWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version of Google Wave Notifier.
        /// </summary>
        internal static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new version of Google Wave Notifier available.
        ///
        ///New version: {0}
        ///Your version: {1}
        ///
        ///Click here to visit the download page..
        /// </summary>
        internal static string NewVersionAvailableDescription {
            get {
                return ResourceManager.GetString("NewVersionAvailableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no unread messages..
        /// </summary>
        internal static string NoNewMessagesTooltip {
            get {
                return ResourceManager.GetString("NoNewMessagesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Google &amp;Wave.
        /// </summary>
        internal static string OpenGoogleWave {
            get {
                return ResourceManager.GetString("OpenGoogleWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Google password. This is stored only on your machine, and only ever transmitted to Google via SSL..
        /// </summary>
        internal static string PasswordDescription {
            get {
                return ResourceManager.GetString("PasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Sounds.
        /// </summary>
        internal static string PlaySounds {
            get {
                return ResourceManager.GetString("PlaySounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select whether you&apos;d like Google Wave Notifier to play the Windows New Mail sound when it finds new messages..
        /// </summary>
        internal static string PlaySoundsDescription {
            get {
                return ResourceManager.GetString("PlaySoundsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        internal static string PreferredBrowser {
            get {
                return ResourceManager.GetString("PreferredBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the browser you would like to use when launching wave..
        /// </summary>
        internal static string PreferredBrowserDescription {
            get {
                return ResourceManager.GetString("PreferredBrowserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string PreferredCulture {
            get {
                return ResourceManager.GetString("PreferredCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the language you would like Google Wave Notifier to use. Changing this value will cause the application to restart with your new language..
        /// </summary>
        internal static string PreferredCultureDescription {
            get {
                return ResourceManager.GetString("PreferredCultureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Address.
        /// </summary>
        internal static string ProxyAddress {
            get {
                return ResourceManager.GetString("ProxyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have a proxy server, enter the address of it here (in the form http://proxyname:port/)..
        /// </summary>
        internal static string ProxyAddressDescription {
            get {
                return ResourceManager.GetString("ProxyAddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Password.
        /// </summary>
        internal static string ProxyPassword {
            get {
                return ResourceManager.GetString("ProxyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your proxy server requires a password, please enter it here..
        /// </summary>
        internal static string ProxyPasswordDescription {
            get {
                return ResourceManager.GetString("ProxyPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Server.
        /// </summary>
        internal static string ProxyServer {
            get {
                return ResourceManager.GetString("ProxyServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Username.
        /// </summary>
        internal static string ProxyUsername {
            get {
                return ResourceManager.GetString("ProxyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your proxy server requires a username, please enter it here..
        /// </summary>
        internal static string ProxyUsernameDescription {
            get {
                return ResourceManager.GetString("ProxyUsernameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Bug / Suggestion.
        /// </summary>
        internal static string ReportBugOrSuggestion {
            get {
                return ResourceManager.GetString("ReportBugOrSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run At Startup.
        /// </summary>
        internal static string RunAtStartup {
            get {
                return ResourceManager.GetString("RunAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select whether you&apos;d like Google Wave Notifier to start up when Windows starts..
        /// </summary>
        internal static string RunAtStartupDescription {
            get {
                return ResourceManager.GetString("RunAtStartupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please configure settings and preferences below. Please pay attention to the descriptions shown in the bottom pane when you select an option..
        /// </summary>
        internal static string SettingsIntro {
            get {
                return ResourceManager.GetString("SettingsIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Click Check.
        /// </summary>
        internal static string SingleClickCheck {
            get {
                return ResourceManager.GetString("SingleClickCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select whether you&apos;d like Google Wave Notifier to force a check for new messages when you click the icon in the system tray..
        /// </summary>
        internal static string SingleClickCheckDescription {
            get {
                return ResourceManager.GetString("SingleClickCheckDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        internal static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load Inbox.
        /// </summary>
        internal static string UnableToLoadInbox {
            get {
                return ResourceManager.GetString("UnableToLoadInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load your Google Wave inbox. It&apos;s possible Google have changed the web application. Please look out for a new version of Google Wave Notifier!.
        /// </summary>
        internal static string UnableToLoadInboxDescription {
            get {
                return ResourceManager.GetString("UnableToLoadInboxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse Inbox.
        /// </summary>
        internal static string UnableToParseInbox {
            get {
                return ResourceManager.GetString("UnableToParseInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse your Google Wave inbox. It&apos;s possible Google have changed the web application. Please look out for a new version of Google Wave Notifier!.
        /// </summary>
        internal static string UnableToParseInboxDescription {
            get {
                return ResourceManager.GetString("UnableToParseInboxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred. It&apos;s possible Google have changed the web application. Please report a bug including the contents of the error log file..
        /// </summary>
        internal static string UnknownErrorDescription {
            get {
                return ResourceManager.GetString("UnknownErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Wave Notifier requires .NET 3.5 SP1. Please check you have this installed and restart the application..
        /// </summary>
        internal static string UnknownErrorDescriptionDotNet {
            get {
                return ResourceManager.GetString("UnknownErrorDescriptionDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Google username. This is the bit before @googlewave.com. Do not include @googlewave.com!.
        /// </summary>
        internal static string UsernameDescription {
            get {
                return ResourceManager.GetString("UsernameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username should not include @googlewave.com..
        /// </summary>
        internal static string UsernameWarningText {
            get {
                return ResourceManager.GetString("UsernameWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave.
        /// </summary>
        internal static string Wave {
            get {
                return ResourceManager.GetString("Wave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
